-- Tablas para clasificación de números (Active/Inactive)

-- Tabla para contactos activos (Validados)
create table if not exists active_contacts (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  user_name text,
  locale text default 'es',
  classified_at timestamptz default timezone('utc'::text, now()),
  classification_details jsonb, -- Guardar el resultado exacto (ANSWER, BUSY, etc)
  times_called int default 0,
  last_called_at timestamptz,
  created_at timestamptz default timezone('utc'::text, now())
);

-- Tabla para contactos inactivos (Desconectados/Invalidos)
create table if not exists inactive_contacts (
  id bigint generated by default as identity primary key,
  phone text not null,
  user_name text,
  locale text default 'es',
  classified_at timestamptz default timezone('utc'::text, now()),
  classification_cause text, -- CAUSA (CHANUNAVAIL, CONGESTION, ETC)
  created_at timestamptz default timezone('utc'::text, now())
);

-- Índices para búsqueda rápida
create index if not exists idx_active_contacts_phone on active_contacts(phone);
create index if not exists idx_inactive_contacts_phone on inactive_contacts(phone);

-- (Opcional) Trigger para limpiar de outbound_call_contacts cuando se mueven
-- Por ahora lo haremos por código para tener control.
