-- Tabla para monitoreo en tiempo real de clasificaciones
create table if not exists public.classification_queue (
  id bigint generated by default as identity primary key,
  phone text not null,
  status text default 'pending', -- pending, waiting_entropy, dialing, completed, failed
  result text null, -- active, inactive, indeterminate
  cause text null,
  created_at timestamptz default timezone('utc'::text, now()),
  updated_at timestamptz default timezone('utc'::text, now())
);

-- Indices
create index if not exists idx_classification_queue_created_at on public.classification_queue(created_at desc);
create index if not exists idx_classification_queue_status on public.classification_queue(status);
