create table public.active_contacts (
  id bigint generated by default as identity not null,
  phone text not null,
  user_name text null,
  locale text null default 'es'::text,
  classified_at timestamp with time zone null default timezone ('utc'::text, now()),
  classification_details jsonb null,
  times_called integer null default 0,
  last_called_at timestamp with time zone null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint active_contacts_pkey primary key (id),
  constraint active_contacts_phone_key unique (phone)
) TABLESPACE pg_default;

create index IF not exists idx_active_contacts_phone on public.active_contacts using btree (phone) TABLESPACE pg_default;

create table public.call_transfers (
  id text not null,
  retell_call_id text not null,
  phone text not null,
  reason text null,
  priority text null default 'normal'::text,
  status text null default 'pending'::text,
  agent_id text null,
  created_at timestamp without time zone null default now(),
  accepted_at timestamp without time zone null,
  completed_at timestamp without time zone null,
  constraint call_transfers_pkey primary key (id),
  constraint call_transfers_priority_check check (
    (
      priority = any (array['urgent'::text, 'normal'::text])
    )
  ),
  constraint call_transfers_status_check check (
    (
      status = any (
        array[
          'pending'::text,
          'accepted'::text,
          'rejected'::text,
          'completed'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_transfers_status on public.call_transfers using btree (status, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_transfers_agent on public.call_transfers using btree (agent_id) TABLESPACE pg_default;


create table public.chat_memory_instagram_temp (
  id serial not null,
  session_id character varying(255) not null,
  message jsonb not null,
  created_at timestamp with time zone not null default now(),
  constraint chat_memory_instagram_temp_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_chat_memory_ig_temp_session on public.chat_memory_instagram_temp using btree (session_id, created_at) TABLESPACE pg_default;

create table public.inactive_contacts (
  id bigint generated by default as identity not null,
  phone text not null,
  user_name text null,
  locale text null default 'es'::text,
  classified_at timestamp with time zone null default timezone ('utc'::text, now()),
  classification_cause text null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint inactive_contacts_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_inactive_contacts_phone on public.inactive_contacts using btree (phone) TABLESPACE pg_default;

create table public.out_customers (
  id bigserial not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  user_name text null,
  user_number text not null,
  user_wa_number text null,
  locale text null default 'es'::text,
  interest_first text null,
  interest_second text null,
  qualified text null,
  qualified_for text null,
  conversations jsonb null default '[]'::jsonb,
  last_call_id text null,
  last_interaction_ts timestamp with time zone null,
  wa_sending boolean null default false,
  wa_number_backup text null,
  conversation_context jsonb null default '{}'::jsonb,
  last_wa_interaction timestamp with time zone null,
  wa_consent_received boolean null default false,
  trees_interested_count integer null default 0,
  interaction_stage text null default 'initial'::text,
  constraint our_customers_pkey primary key (id),
  constraint our_customers_user_number_key unique (user_number),
  constraint user_number_format check ((user_number ~ '^\+[0-9]+$'::text))
) TABLESPACE pg_default;

create index IF not exists idx_our_customers_user_number on public.out_customers using btree (user_number) TABLESPACE pg_default;

create index IF not exists idx_our_customers_locale on public.out_customers using btree (locale) TABLESPACE pg_default;

create index IF not exists idx_our_customers_qualified on public.out_customers using btree (qualified) TABLESPACE pg_default;

create index IF not exists idx_our_customers_last_interaction on public.out_customers using btree (last_interaction_ts desc) TABLESPACE pg_default;

create index IF not exists idx_our_customers_conversations on public.out_customers using gin (conversations) TABLESPACE pg_default;

create index IF not exists idx_out_customers_user_number on public.out_customers using btree (user_number) TABLESPACE pg_default;

create index IF not exists idx_out_customers_qualified_stage on public.out_customers using btree (qualified, interaction_stage) TABLESPACE pg_default;

create trigger update_our_customers_updated_at BEFORE
update on out_customers for EACH row
execute FUNCTION update_updated_at_column ();

create table public.outbound_call_contacts (
  phone text not null,
  user_name text null,
  locale text not null default 'es'::text,
  called boolean not null default false,
  times_called integer not null default 0,
  created_at timestamp with time zone null default now(),
  last_call_attempt timestamp with time zone null,
  last_call_result text null,
  do_not_call boolean null default false,
  notes text null,
  constraint outbound_call_contacts_pkey primary key (phone)
) TABLESPACE pg_default;

create index IF not exists idx_outbound_call_contacts_called on public.outbound_call_contacts using btree (called, last_call_attempt desc) TABLESPACE pg_default;


create table public.outbound_call_queue (
  phone text not null,
  user_name text null,
  locale text null default 'es'::text,
  status text null default 'queued'::text,
  retell_call_id text null,
  updated_at timestamp without time zone null default now(),
  id bigserial not null,
  created_at timestamp with time zone null default now(),
  from_number text null,
  job_id text null,
  active boolean null default true,
  call_duration_seconds integer null,
  end_reason text null,
  constraint outbound_call_queue_pkey primary key (id),
  constraint outbound_call_queue_status_check check (
    (
      status = any (
        array[
          'queued'::text,
          'calling'::text,
          'active'::text,
          'finished'::text,
          'voicemail'::text,
          'no_answer'::text,
          'busy'::text,
          'failed'::text,
          'short_call'::text,
          'callback'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_outbound_call_queue_phone on public.outbound_call_queue using btree (phone) TABLESPACE pg_default;

create index IF not exists idx_outbound_call_queue_status on public.outbound_call_queue using btree (status) TABLESPACE pg_default
where
  (active = true);

create index IF not exists idx_outbound_call_queue_job_id on public.outbound_call_queue using btree (job_id) TABLESPACE pg_default;

create index IF not exists idx_outbound_call_queue_created_at on public.outbound_call_queue using btree (created_at desc) TABLESPACE pg_default;

create trigger update_outbound_call_queue_updated_at BEFORE
update on outbound_call_queue for EACH row
execute FUNCTION update_updated_at_column ();

create table public.retell_agents (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  language text null,
  name character varying null,
  description text null,
  call_direction text null,
  agent_id text null,
  constraint retell_agents_pkey primary key (id)
) TABLESPACE pg_default;

create table public.whatsapp_messages (
  id bigserial not null,
  customer_phone text not null,
  message_id text null,
  direction text not null,
  message_text text not null,
  sender text not null,
  recipient text not null,
  ai_response text null,
  ai_model text null default 'phi3:mini'::text,
  context_used jsonb null,
  created_at timestamp with time zone null default now(),
  thread_id text null,
  sentiment text null,
  intent text null,
  metadata jsonb null default '{}'::jsonb,
  status text not null default 'unknown'::text,
  msg_type text not null default 'text'::text,
  lang text null,
  error text null,
  constraint whatsapp_messages_pkey primary key (id),
  constraint whatsapp_messages_message_id_key unique (message_id)
) TABLESPACE pg_default;

create index IF not exists idx_wa_customer_phone on public.whatsapp_messages using btree (customer_phone, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_wa_thread on public.whatsapp_messages using btree (thread_id, created_at) TABLESPACE pg_default;

create index IF not exists idx_wa_created on public.whatsapp_messages using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_wa_status_created on public.whatsapp_messages using btree (status, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_whatsapp_messages_customer_phone on public.whatsapp_messages using btree (customer_phone) TABLESPACE pg_default;


-- Tabla para monitoreo en tiempo real de clasificaciones
create table if not exists public.classification_queue (
  id bigint generated by default as identity primary key,
  phone text not null,
  status text default 'pending', -- pending, waiting_entropy, dialing, completed, failed
  result text null, -- active, inactive, indeterminate
  cause text null,
  created_at timestamptz default timezone('utc'::text, now()),
  updated_at timestamptz default timezone('utc'::text, now())
);

-- Indices
create index if not exists idx_classification_queue_created_at on public.classification_queue(created_at desc);
create index if not exists idx_classification_queue_status on public.classification_queue(status);
